### ISSUE TITLE
最新版本还是不能使用视频自动慢速

### ISSUE THREAD

**Issue by yousei521** [jianchang512/pyvideotrans#129]
![11](https://github.com/jianchang512/pyvideotrans/assets/125034389/f6a0c83e-5adb-45d4-9d99-d6b7d36c6ce8)
再提个建议。能不能把 等待修改时间改成5秒左右，或者给个自定义设置也可以。1分钟时间实在太长了。

非常感谢！

**Comment by yousei521** [comment]
![1111](https://github.com/jianchang512/pyvideotrans/assets/125034389/2173edbf-6f8a-4516-9330-f9fa5fcc136f)
图片贴错了。是这张

**Comment by yousei521** [comment]
另外一个建议就是配音自动加速和视频自动加速都不选的时候，不要剪切音频，把音频做整体的加速或者慢速到视频同样长的时间，我以前就是这样做的。不过是pr里面一个个的做太累了。对于学习一点外文视频。稍微对不上不影响。再次感谢你的付出！

**Comment by jianchang512** [comment]
[解压覆盖sp.exe文件.zip](https://github.com/jianchang512/pyvideotrans/files/13655945/sp.exe.zip)

cuda出错的问题试试解压覆盖 sp.exe

**Comment by Bob8852** [comment]
> [解压覆盖sp.exe文件.zip](https://github.com/jianchang512/pyvideotrans/files/13655945/sp.exe.zip)
> 
> cuda错误的问题尝试解压覆盖sp.exe

下载了最新版本，也覆盖了sp.exe，FFmpeg仍然报错

**Comment by Bob8852** [comment]
大神，仍然没有解决报错问题如图，但是软件真的是做的很强大，赞
![Uploading cuda报错.png…]()

**Comment by jianchang512** [comment]
报错信息呢，详细信息

**Comment by Bob8852** [comment]
> 报错信息呢，详细信息

[
![cuda报错](https://github.com/jianchang512/pyvideotrans/assets/85837158/61b80044-c177-4910-b840-b0a313617218)
](url)

**Comment by Bob8852** [comment]
> 报错信息呢，详细信息

就是上图的报错信息

**Comment by jianchang512** [comment]
> > 报错信息呢，详细信息
> 
> 就是上图的报错信息



在 sp.exe 目录下，打开cmd窗口，文件夹地址栏输入 " cmd " 回车。然后执行这个命令

`ffmpeg  -hide_banner -hwaccel cuda -y -i D:/download/videoplayback.mp4 -an -c:v h264_nvenc  novoice.mp4`

确保 videoplayback.mp4 存在，然后看看报什么错

**Comment by Bob8852** [comment]
> ffmpeg -hide_banner -hwaccel cuda -y -i D:/download/videoplayback.mp4 -an -c:v h264_nvenc novoice.mp4

按你的命令输入后报如下错误：
D:\download\video-trans-0.970>ffmpeg  -hide_banner -hwaccel cuda -y -i D:/download/videoplayback.mp4 -an -c:v h264_nvenc  novoice.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:/download/videoplayback.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2021-07-20T07:39:41.000000Z
  Duration: 00:01:42.75, start: 0.000000, bitrate: 279 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 640x360 [SAR 1:1 DAR 16:9], 147 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      creation_time   : 2021-07-20T07:39:41.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 07/20/2021.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2021-07-20T07:39:41.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 07/20/2021.
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_nvenc))
Press [q] to stop, [?] for help
[h264_nvenc @ 000002afe0e0c5c0] Driver does not support the required nvenc API version. Required: 12.1 Found: 11.1
[h264_nvenc @ 000002afe0e0c5c0] The minimum required Nvidia driver for nvenc is (unknown) or newer
[vost#0:0/h264_nvenc @ 000002afe10a4680] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
Error while filtering: Function not implemented
[out#0/mp4 @ 000002afe0e48d80] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=N/A bitrate=N/A speed=N/A
Conversion failed!

**Comment by Bob8852** [comment]
我的显卡是3090

**Comment by Bob8852** [comment]
> ffmpeg -hide_banner -hwaccel cuda -y -i D:/download/videoplayback.mp4 -an -c:v h264_nvenc novoice.mp4

我的报错是因为我的显卡驱动不是最新版本，我升级了一下，可以正常解码了，启用cuda不在报错，感谢大神的力作

**Comment by yousei521** [comment]
你好。2个模式已经都可以使用了。希望能把等待时间改成5秒，

如果2个模式都不选择的话还是会报错。报错代码如下：0秒后自动合并，你可以停止倒计时后去修改字幕，以便配音更准确
开始配音操作:edgeTTS,zh-CN-YunxiNeural
offset=26424>0，需要末尾添加延长视频帧 26424 ms
出错:ffmpeg执行结果:失败 cmd=['ffmpeg', '-hide_banner', '-hwaccel', 'cuda', '-loop', '1', '-i', 'F:/video-trans/tmp/09 Using Vectors for unlimited Zoom without loosing quality (no pixelation)/last.jpg', '-vf', 'fps=30.0,scale_cuda=1920:1080', '-c:v', 'h264_nvenc', '-crf', '0', '-to', '00:00:26.424', '-pix_fmt', 'yuv420p', '-y', 'F:/video-trans/tmp/09 Using Vectors for unlimited Zoom without loosing quality (no pixelation)/last_clip.mp4'], errs='Error reinitializing filters!\\r\\nFailed to inject frame into filter network: Function not implemented\\r\\nError while filtering: Function not implemented\\r\\n[out#0/mp4 @ 0000021d09eb0980] Nothing was written into output file, because at least one of its streams received no packets.\\r\\nframe= 0 fps=0.0 q=0.0 Lsize= 0kB time=N/A bitrate=N/A speed=N/A \\r\\nConversion failed!\\r\\n"'
执行ffmpeg失败:errs='Error reinitializing filters!\\r\\nFailed to inject frame into filter network: Function not implemented\\r\\nError while filtering: Function not implemented\\r\\n[out#0/mp4 @ 0000021d09eb0980] Nothing was written into output file, because at least one of its streams received no packets.\\r\\nframe= 0 fps=0.0 q=0.0 Lsize= 0kB time=N/A bitrate=N/A speed=N/A \\r\\nConversion failed!\\r\\n"'出错:末尾添加延长视频帧失败，将保持原样，截断音频,不延长视频
配音结束

进行最后一步合成处理


:::开始处理第2个视频(共3个):【D:/CTA5study/10 How Springs create Follow Through and Overlapping Action Automatically.mp4】
开始将音视频分离
10 How Springs create Follow Through and Overlapping Action Automatically 分析视频数据
开始语音识别以提取字幕

进行整体语音识别,可能耗时较久，请等待:base模型
语音识别出错了
:::开始处理第3个视频(共3个):【D:/CTA5study/11 How FFD makes it easier for Exaggeration and Squash and Stretch.mp4】
开始将音视频分离
11 How FFD makes it easier for Exaggeration and Squash and Stretch 分析视频数据
开始语音识别以提取字幕

进行整体语音识别,可能耗时较久，请等待:base模型
语音识别出错了
本次任务全部结束

**Comment by yousei521** [comment]
忘记说了。是批量生成的时候报错。就是2个模式都不选。如果选一个的话都正常。

**Comment by jianchang512** [comment]
1. 没有出错信息，看不出错误
2. 时间倒计时5秒没意义，来不及看清和操作，60s如果嫌长，完全可以手动直接点击“继续”就可以了
