### ISSUE TITLE
Source lang

### ISSUE THREAD

**Issue by andreygrinchuk** [jianchang512/pyvideotrans#365]
Hi, in source lang, I can't find Ukrainian. 
 I tried to add on my own as well as changing voice to "uk-UA-OstapNeural" and "uk-UA-PolinaNeural" manually but it did not work. 
 Is there a way to do this on my own in order not to bother you?

**Comment by jianchang512** [comment]
No languages can be added because the first step of speech recognition relies on the whisper model, which supports a limited number of languages, and what it doesn't support can't be added.

**Comment by andreygrinchuk** [comment]
They updated the language list drastically then because Open AI supports all these languages as of now-

Afrikaans, Arabic, Armenian, Azerbaijani, Belarusian, Bosnian, Bulgarian, Catalan, Chinese, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, Galician, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Italian, Japanese, Kannada, Kazakh, Korean, Latvian, Lithuanian, Macedonian, Malay, Marathi, Maori, Nepali, Norwegian, Persian, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Tagalog, Tamil, Thai, Turkish, Ukrainian, Urdu, Vietnamese, and Welsh.


Hence, I have a question about adding something myself.

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/de0da443-5cbc-4b7c-9c06-25bd91c07f8b)
This is all the languages that the openai-whisper model can support.

It is difficult to add languages in a few words, because different translation channels require different language codes for the same language, and different languages require different 3-digit language codes for embedding soft subtitles. To add a language, you need to change the interface language translation file, the translation channel code file, the TTS dubbing file, and you need to look up the language code of that language for each translation channel under this channel.

Ukrainian can be added in the next version

**Comment by jianchang512** [comment]
1.58 had add uk
