### ISSUE TITLE
Custom Font Style for Merging Subtitle Video

### ISSUE THREAD

**Issue by rafahoff** [jianchang512/pyvideotrans#467]
Hi!

If possible, please add the GUI or set.ini settings for customizing the font style when merging subtitles with the video. 
Mainly for the font color and background color.

Reference for ffmpeg font style:
https://www.bannerbear.com/blog/how-to-add-subtitles-to-a-video-with-ffmpeg-5-different-styles/
Example:
`ffmpeg -i input.mp4 -vf "subtitles=subtitle.srt:force_style='Fontname=Roboto,OutlineColour=&H40000000,BorderStyle=3'" output.mp4`

GUI windows:
![image](https://github.com/jianchang512/pyvideotrans/assets/49349559/8b209c0e-8b88-457a-86aa-2b57928167c0)

Set.ini:
![image](https://github.com/jianchang512/pyvideotrans/assets/49349559/9f002a0e-7916-4e6d-a3db-ad216bf4e5a6)

Source code:
![image](https://github.com/jianchang512/pyvideotrans/assets/49349559/e8171480-28a6-418f-92ea-c78282e5c0cf)

**Comment by jianchang512** [comment]
![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/c9fa7540-2f33-44ce-9071-4aa0f63916f7)


![image](https://github.com/jianchang512/pyvideotrans/assets/3378335/727b2a9e-8425-4c95-9326-20ced827b047)


; hard subtitles to use the name of the font, note that not the name of the font file, but the name of the display, such as bold, 宋体, etc.
If you don't know the name of the font, you can create a word document, select the font you want to use, and check the name.
Make sure you fill in the font name correctly, otherwise the subtitle may not be displayed or may not be displayed with the specified font.

Translated with DeepL.com (free version)

**Comment by jianchang512** [comment]
update to lastest
