### ISSUE TITLE
会自己调用gpu吗

### ISSUE THREAD

**Issue by zxdmrg** [jianchang512/pyvideotrans#6]
设备：amd的5800u自带核显。
问题：测试只能调用cpu，速度很慢。之前用过WhisperDesktop这个开源软件它可以调用gpu。速度快很多，不知道这个项目可以实现吗？

**Comment by SingingDalong** [comment]
I feel the same way. If the pyvideotrans tool could use GPU like WhisperDesktop, it would be faster.

**Comment by jianchang512** [comment]
后续可能会加个支持GPU的分支吧，因为torch、cuda、N卡驱动版本对应关系问题，集成在一起，可能导致在一些环境下无法运行或者出错。项目的目标是希望提供一个足够简单的工具，只需CPU，不必懂版本关系即可轻松使用

目前可以源码部署下，然后替换里面的torch版本为cuda版，whisper默认cuda有效时就会优先使用

In the future, a branch that supports GPU may be added. Because of the corresponding relationship between torch, cuda, and N card driver versions, the integration may lead to inability to run or errors in some environments.
